import type { Metadata } from "next";

export const metadata: Metadata = { title: "예배 안내" };

export default function WorshipPage() {
  return <div className="subpage"><main id="main-content">
    <section className="archive-hero archive-hero--worship" aria-labelledby="worship-page-title"><div className="page-shell archive-hero__inner"><div><p className="eyebrow">WORSHIP WITH US</p><h1 id="worship-page-title">이번 주일,<br/>편안하게 오세요.</h1></div><p>예배 시간과 장소를 먼저 확인하고,<br/>처음 오시는 분도 부담 없이 준비할 수 있도록 안내합니다.</p></div></section>
    <section className="worship worship-page-section section" aria-labelledby="worship-schedule-title"><div className="worship__orb worship__orb--one"/><div className="worship__orb worship__orb--two"/><div className="page-shell worship__grid"><div className="section-heading"><p className="eyebrow">WEEKLY SCHEDULE</p><h2 id="worship-schedule-title">함께 드리는<br/>예배입니다.</h2><p>아래 시간은 레이아웃 확인을 위한 예시입니다. 운영 전 실제 예배 시간으로 확인해 주세요.</p></div><div className="schedule"><article className="schedule__primary"><p>주일예배</p><strong>10:30</strong><div><span>매주 일요일</span><span>시간 확인 필요</span></div></article><article><div><p>어린이예배</p><span>4세–초등학생 · 꿈마루 1층</span></div><strong>10:30</strong></article><article><div><p>청년예배</p><span>대학생·청년 · 지유쓰</span></div><strong>14:00</strong></article><article><div><p>수요기도회</p><span>누구나 · 작은예배실 3층</span></div><strong>19:30</strong></article></div></div></section>
    <section className="worship-visit section" aria-labelledby="worship-visit-title"><div className="page-shell worship-visit__grid"><div className="section-heading"><p className="eyebrow">YOUR FIRST VISIT</p><h2 id="worship-visit-title">처음 오신다면<br/>이렇게 준비하세요.</h2></div><div className="worship-visit__copy"><ol><li><strong>예배 10분 전 도착</strong><span>예배당 위치를 천천히 확인하고 안내를 받을 수 있어요.</span></li><li><strong>편안한 복장</strong><span>정해진 복장은 없습니다. 편안한 마음으로 오세요.</span></li><li><strong>궁금한 점은 현장에서</strong><span>처음 방문했다고 알려주시면 필요한 안내를 도와드립니다.</span></li></ol></div></div></section>
    <section className="worship-location section" aria-labelledby="worship-location-title"><div className="page-shell worship-location__inner"><div><p className="eyebrow">LOCATION</p><h2 id="worship-location-title">경기도 시흥시<br/>하상로8번길 12-1</h2></div><div><p>글로벌교회</p><a className="button button--dark" href="https://share.google/0DF5W8pHQeUwgCa4t" target="_blank" rel="noopener noreferrer">지도에서 길 찾기</a></div></div></section>
  </main></div>;
}
